apiVersion: batch/v1
kind: Job
metadata:
  name: qwen-embed-job
  labels:
    app: qwen-embed
    component: embedding
spec:
  template:
    spec:
      containers:
        - name: qwen-embed-container
          image: docker.io/malcolmgreaves/daft-qwen3-text-embedding:latest
          command: ["python", "-m", "cc_embed.main_pipeline"]
          resources:
            requests:
              cpu: "8"
              memory: "32Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "16"
              memory: "64Gi"
              nvidia.com/gpu: "1"
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: INPUT
              value: "s3://commoncrawl/crawl-data/CC-MAIN-2025-08/segments/*/warc/*"
            - name: OUTPUT
              value: ""
            - name: LIMIT
              value: ""
            - name: IS_PARQUET
              value: "0"
            - name: MAX_SEQ_LEN_SPACY
              value: "100000"
            - name: MAX_SEQ_LEN_SENTENCE_TRANSFORMER
              value: "8192"
            - name: NUM_GPU_NODES
              value: "1"
            - name: NLP_MODEL_NAME
              value: "en_core_web_sm"
            - name: EMBEDDING_MODEL_NAME
              value: "Qwen/Qwen3-Embedding-0.6B"
            - name: DEVICE
              value: ""
            - name: CHUNKING_PARALLELISM
              value: "8"
            - name: BATCH_SIZE
              value: "512"
            - name: SENTENCE_TRANSFORMER_BATCH_SIZE
              value: "16"
            - name: ENCODING_DIM
              value: "1024"
      restartPolicy: Never
      nodeSelector:
        k8s.eventual.io/node-role: textembed-sm
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
  backoffLimit: 4
  activeDeadlineSeconds: 86400 # 24 hours
